# Generated by Django 6.0.3 on 2026-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidade',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='icone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
